# Generated by Django 2.1 on 2018-11-30 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng 0xxxxxxxxxxx.', regex='^\\0\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
