# Generated by Django 2.1 on 2018-12-02 15:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carservice', '0002_auto_20181130_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('date_enxpense', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('decription', models.CharField(max_length=2000, null=True)),
                ('type_cost', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='email',
            field=models.EmailField(default='lephuocnhankn@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='content',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng 0xxxxxxxxxxx.', regex='^[0-9]{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='content',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng 0xxxxxxxxxxx.', regex='^[0-9]{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
