# Generated by Django 2.1 on 2018-12-07 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0003_auto_20181202_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_img', models.ImageField(blank=True, upload_to='car/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Car')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
